# Modified version of the 'tokyo-night' theme
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[░▒▓](os_bg)\
$os\
[](bg:dir_bg fg:os_bg)\
$directory\
[](bg:git_bg fg:dir_bg)\
$git_branch\
$git_status\
[](bg:env_bg fg:git_bg)\
$golang\
$nodejs\
$php\
$python\
$rust\
[](fg:env_bg bg:user_bg)\
$username\
$character\
[](fg:user_bg) """

right_format = """
[](fg:right_bg)\
$cmd_duration\
$time\
[▓▒░](fg:right_bg)\
"""

palette = "carbonfox"
[palettes.carbonfox]
red = "#ee5396"
green = "#25be6a"
yellow = "#08bdba" # 'yellow' (cyan)
blue = "#78a9ff"
purple = "#be95ff" # magenta base
cyan = "#33b1ff"
white = "#dfdfe0"
orange = "#3ddbd9" # 'orange' (cyan/teal)
pink = "#ff7eb6"
#---
os_bg = "#ee5396" # carbonfox red base
dir_bg = "#be95ff" # carbonfox magenta base
git_bg = "#33b1ff" # carbonfox cyan base
env_bg = "#3ddbd9" # carbonfox 'orange' base
user_bg = "#08bdba" # carbonfox 'yellow' base
right_bg = "#353535" # carbonfox bg3

os_fg = "#282828"
dir_fg = "#282828"
git_fg = "#282828"
env_fg = "#282828"
user_fg = "#282828"
right_fg = "#f2f4f8" # carbonfox fg1
#right_fg = "#b6b8bb" # carbonfox fg2
#right_fg = "#7b7c7e" # carbonfox fg3

[character]
format = "$symbol"
success_symbol = ''
error_symbol = '[  ](fg:user_fg bg:user_bg)' # No $character level `style` option
vimcmd_symbol = '[  ](fg:user_fg bg:user_bg)'
vimcmd_replace_one_symbol = '[](fg:user_fg bg:user_bg)'
vimcmd_replace_symbol = '[](fg:user_fg bg:user_bg)'
vimcmd_visual_symbol = '[](fg:user_fg bg:user_bg)'

[cmd_duration]
min_time = 1500
style = "bg:right_bg fg:right_fg"
format = '[ $duration]($style)'

[directory]
style = "fg:dir_fg bg:dir_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:git_bg fg:git_fg"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:git_bg fg:git_fg"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "bg:env_bg fg:env_fg"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "󰌠"
# Warning: `uv` can run any binary at `.venv/bin/python` without interaction
python_binary = [['uv', 'run', '--no-python-downloads', '--no-project', 'python']]
style = "bg:env_bg fg:env_fg"
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:env_bg fg:env_fg"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "bg:env_bg fg:env_fg"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ""
style = "bg:env_bg fg:env_fg"
format = '[ $symbol ($version) ]($style)'

[os]
style = "bg:os_bg fg:os_fg"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:right_bg fg:right_fg"
format = '[ $time]($style)'

[username]
disabled = false
style_user = "bg:user_bg fg:user_fg"
style_root = "bg:user_bg fg:red"
format = "[ $user ]($style)"
