# Modified version of the 'tokyo-night' theme
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[░▒▓](os_bg)\
$os\
[](bg:dir_bg fg:os_bg)\
$directory\
[](bg:git_bg fg:dir_bg)\
$git_branch\
$git_status\
[](bg:env_bg fg:git_bg)\
$nodejs\
$rust\
$golang\
$php\
[](fg:env_bg bg:user_bg)\
$username\
[](fg:user_bg) """

right_format = """
$character
[](fg:right_bg)\
[$cmd_duration ](bg:right_bg)\
$time\
[▓▒░](fg:right_bg)\
"""

palette = "carbonfox"
[palettes.carbonfox]
red = "#ee5396"
green = "#25be6a"
yellow = "#08bdba" # 'yellow' (cyan)
blue = "#78a9ff"
purple = "#be95ff" # magenta base
cyan = "#33b1ff"
white = "#dfdfe0"
orange = "#3ddbd9" # 'orange' (cyan/teal)
pink = "#ff7eb6"
#--- 
os_bg = "#ee5396" # carbonfox red base
dir_bg = "#be95ff" # carbonfox magenta base
git_bg = "#33b1ff" # carbonfox cyan base
env_bg = "#3ddbd9" # carbonfox 'orange' base
user_bg = "#08bdba" # carbonfox 'yellow' base
right_bg = "#353535" # carbonfox bg3

os_fg = "#282828" 
dir_fg = "#282828" 
git_fg = "#282828"
env_fg = "#282828"
user_fg = "#282828"
right_fg = "#f2f4f8" # carbonfox fg1
#right_fg = "#b6b8bb" # carbonfox fg2
#right_fg = "#7b7c7e" # carbonfox fg3

[character]
success_symbol = ""
error_symbol = '[](bold red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:yellow)'

[cmd_duration]
min_time = 1500
format = " $duration"

[directory]
style = "fg:dir_fg bg:dir_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:git_bg"
format = '[[ $symbol $branch ](fg:git_fg bg:git_bg)]($style)'

[git_status]
style = "bg:git_bg"
format = '[[($all_status$ahead_behind )](fg:git_fg bg:git_bg)]($style)'

[nodejs]
symbol = ""
style = "bg:env_bg"
format = '[[ $symbol ($version) ](fg:env_fg bg:env_bg)]($style)'

[rust]
symbol = ""
style = "bg:env_bg"
format = '[[ $symbol ($version) ](fg:env_fg bg:env_bg)]($style)'

[golang]
symbol = ""
style = "bg:env_bg"
format = '[[ $symbol ($version) ](fg:env_fg bg:env_bg)]($style)'

[php]
symbol = ""
style = "bg:env_bg"
format = '[[ $symbol ($version) ](fg:env_fg bg:env_bg)]($style)'

[os]
style = "bg:os_bg fg:os_fg"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:right_bg"
format = '[[$time](fg:right_fg bg:right_bg)]($style)'

[username]
disabled = false
style_user = "bg:user_bg fg:user_fg"
style_root = "bg:user_bg fg:red"
format = "[ $user ]($style)"
