# Nightfox colors for Tmux
# Style: carbonfox
# Upstream original: https://github.com/edeneast/nightfox.nvim/raw/main/extra/carbonfox/carbonfox.tmux

# Palette
set -g @black "#0c0c0c"
set -g @light_gray "#b6b8bb"
#set -g @accent "#78a9ff"
set -g @accent "#33b1ff"
set -g @dark_gray "#7b7c7e"

set -g mode-style "fg=#{@black},bg=#{@light_gray}"
set -g message-style "fg=#{@black},bg=#{@light_gray}"
set -g message-command-style "fg=#{@black},bg=#{@light_gray}"
set -g pane-border-style "fg=#{@light_gray}"
set -g pane-active-border-style "fg=#{@accent}"
set -g status "on"
set -g status-justify "left"
set -g status-style "fg=#{@light_gray},bg=#{@black}"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE
set -g status-left "#[fg=#{@black},bg=#{@accent},bold] #S #[fg=#{@accent},bg=#{@black},nobold,nounderscore,noitalics]"
set -g status-right "#[fg=#{@black},bg=#{@black},nobold,nounderscore,noitalics]#[fg=#{@accent},bg=#{@black}] #{prefix_highlight} #[fg=#{@light_gray},bg=#{@black},nobold,nounderscore,noitalics]#[fg=#{@black},bg=#{@light_gray}] %Y-%m-%d  %I:%M %p #[fg=#{@accent},bg=#{@light_gray},nobold,nounderscore,noitalics]#[fg=#{@black},bg=#{@accent},bold] #h "
setw -g window-status-activity-style "underscore,fg=#{@dark_gray},bg=#{@black}"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#{@dark_gray},bg=#{@black}"
setw -g window-status-format "#[fg=#{@black},bg=#{@black},nobold,nounderscore,noitalics]#[default] #I  #W#{?window_activity_flag, 󰍩,} #[fg=#{@black},bg=#{@black},nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=#{@black},bg=#{@light_gray},nobold,nounderscore,noitalics]#[fg=#{@black},bg=#{@light_gray},bold] #I  #W#{?window_zoomed_flag, 󰍉,} #[fg=#{@light_gray},bg=#{@black},nobold,nounderscore,noitalics]"
